version: 2
updates:
  - package-ecosystem: pip
    directory: /src/github-copilot-activity
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
